<a href="https://colab.research.google.com/github/ZERuAaaaa/MultiAProj/blob/master/HPC-cw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import time

import numpy as np
from numba import njit
import timeit
import csv

def slow_matrix_product(mat1, mat2):
    """Multiply two matrices."""
    assert mat1.shape[1] == mat2.shape[0]
    result = []
    for c in range(mat2.shape[1]):
        column = []
        for r in range(mat1.shape[0]):
            value = 0
            for i in range(mat1.shape[1]):
                value += mat1[r, i] * mat2[i, c]
            column.append(value)
        result.append(column)
    return np.array(result).transpose()

def fast_matrix_product(matrix1, matrix2):
    assert matrix1.shape[0] == matrix2.shape[1]
    result = []
    for a in range(matrix2.shape[1]):
        row = []
        for b in range(matrix1.shape[0]):
            value = np.dot(matrix1[b],matrix2.transpose()[a])
            row.append(value)
        result.append(row)
    return np.array(result).transpose()

for i in range(1,6):
  test_matrix1 = np.random.rand(i,i)
  test_matrix2 = np.random.rand(i,i)
  print(slow_matrix_product(test_matrix1, test_matrix2))
  print(fast_matrix_product(test_matrix1, test_matrix2))
  assert slow_matrix_product(test_matrix1, test_matrix2).all() == fast_matrix_product(test_matrix1, test_matrix2).all()

print(True)

[[0.20218904]]
[[0.20218904]]
[[0.7889507  0.60727371]
 [0.48474499 0.28552961]]
[[0.7889507  0.60727371]
 [0.48474499 0.28552961]]
[[1.09845922 0.86648064 0.49950246]
 [1.22299356 0.92349727 0.54646818]
 [1.07059492 0.82431542 0.47268096]]
[[1.09845922 0.86648064 0.49950246]
 [1.22299356 0.92349727 0.54646818]
 [1.07059492 0.82431542 0.47268096]]
[[1.8884873  1.37306752 1.39537427 0.95905144]
 [1.01118715 0.64550453 0.92743084 0.52817134]
 [0.85191048 0.75378041 0.97843251 0.71123493]
 [1.42940451 0.99804247 1.11321441 0.74847073]]
[[1.8884873  1.37306752 1.39537427 0.95905144]
 [1.01118715 0.64550453 0.92743084 0.52817134]
 [0.85191048 0.75378041 0.97843251 0.71123493]
 [1.42940451 0.99804247 1.11321441 0.74847073]]
[[1.34229124 1.55124985 1.7337675  1.175536   1.67319325]
 [0.85482654 0.99230197 0.96177392 0.56970848 0.75322917]
 [1.3064033  1.45732754 1.32191411 0.69500463 0.70586598]
 [1.14895153 1.23951068 1.26911492 0.80200865 1.17284111]
 [0.96199751 1.21303767 1.19673822 0.700



```
# Advantage:
1, the old function runs three loop which is O(n^3) time complexity, the modified function runs only two loops which is O(n^2).
2, 
```




In [ ]:
@njit
def numba_fast_matrix_product(matrix1, matrix2):
    assert matrix1.shape[0] == matrix2.shape[1]
    result = []
    for a in range(matrix2.shape[1]):
        row = []
        for b in range(matrix1.shape[0]):
            value = np.dot(matrix1[b],matrix2[a])
            row.append(value)
        result.append(row)
    return result



def test():
    time_slow = []
    time_fast = []
    time_numba = []

    for i in range(0,1000,100):
        test1 = np.random.rand(i,i)
        test2 = np.random.rand(i,i)
        print(i)
        start_time = time.time()
        slow_matrix_product(test1,test2)
        end_time = time.time()
        time_slow.append([i,end_time - start_time])

        start_time = time.time()
        fast_matrix_product(test1,test2)
        end_time = time.time()
        time_fast.append([i,end_time - start_time])

        start_time = time.time()
        numba_fast_matrix_product(test1,test2)
        end_time = time.time()
        time_numba.append([i,end_time - start_time])

    print(time_slow)
    print(time_fast)
    print(time_numba)

test()
